### ISSUE TITLE
Pycrypto on Windows

### ISSUE THREAD

**Issue by poisonfox** [256FF/Refill-uPrint-EEPROMs#1]
Hey,

I have troubles with installing PyCrypto on Windows and I usually use Linux, where installing things usually works easily. But since you provided a batch file I have to use Windows now. Which Python Version an PyCrypto Version have you installed and how did you install PyCrypto?

Currently, I get this running you .bat file:
`Traceback (most recent call last):
  File "C:\Users\Sissy\Desktop\Refill-uPrint-EEPROMs-master\stratasys-cli.py", line 17, in <module>
    from stratasys import crypto
  File "C:\Users\Sissy\Desktop\Refill-uPrint-EEPROMs-master\stratasys\crypto.py", line 6, in <module>
    from Crypto.Cipher import DES, XOR
ImportError: No module named Crypto.Cipher
Traceback (most recent call last):
  File "C:\Users\Sissy\Desktop\Refill-uPrint-EEPROMs-master\stratasys-cli.py", line 17, in <module>
    from stratasys import crypto
  File "C:\Users\Sissy\Desktop\Refill-uPrint-EEPROMs-master\stratasys\crypto.py", line 6, in <module>
    from Crypto.Cipher import DES, XOR
ImportError: No module named Crypto.Cipher
Traceback (most recent call last):
  File "C:\Users\Sissy\Desktop\Refill-uPrint-EEPROMs-master\trans_cp.py", line 12, in <module>
    with open(args.inputfile, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'new.bin'`

**Comment by 256FF** [comment]
I wrote an instruction a time ago: [Preparing windows for running bvanheus stratasys eeprom tool](http://adf.ly/1lwrfm)
